export type Quiz = {
  _id: string;
  course: string;
  title: string;
  published: Boolean;
  description: string;
  type: string;
  points: Number;
  group: string;
  shuffle: Boolean;
  time: Number;
  multiple_attempts: Boolean;
  attempts: Number;
  show_correct: string;
  access_code: string;
  one_question_at_a_time: Boolean;
  webcam: Boolean;
  lock_after_answers: Boolean;
  due: Date;
  available: Date;
  available_until: Date;
};
